#if !canImport(ObjectiveC)
import XCTest

extension FugenToolsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FugenToolsTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FugenToolsTests.__allTests__FugenToolsTests),
    ]
}
#endif
