#if !canImport(ObjectiveC)
import XCTest

extension FugenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FugenTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FugenTests.__allTests__FugenTests),
    ]
}
#endif
