base:
  accessToken: 25961-4ac9fbc9-3bd8-4c43-bbe2-95e477f8a067

colorStyles:
  file: 'https://www.figma.com/file/61xw2FQn61Xr7VVFYwiHHy/Fugen-Demo?version-id=201889163&node-id=14%3A6'
#  file:
#    key: 61xw2FQn61Xr7VVFYwiHHy
#    version: 201889163
#    includedNodes:
#      - 14%3A6
  assets: FugenDemo/Resources/Assets.xcassets/Generated/Colors
  destination: FugenDemo/Generated/ColorStyle.swift
  templateOptions:
    publicAccess: true

textStyles:
#  file: 'https://www.figma.com/file/61xw2FQn61Xr7VVFYwiHHy/Fugen-Demo?version-id=201889163&node-id=15%3A2'
  file:
    key: 61xw2FQn61Xr7VVFYwiHHy
    version: 201889163
    includedNodes:
      - 15%3A2
  destination: FugenDemo/Generated/TextStyle.swift
  templateOptions:
    publicAccess: true
