base:
  accessToken: 41151-2d41cf61-9835-402f-86fe-bbf6d8c3c480

colorStyles:
  file: https://www.figma.com/file/61xw2FQn61Xr7VVFYwiHHy/Fugen-Demo?node-id=91%3A3
  assets: FugenDemo/Resources/Colors.xcassets
  destination: FugenDemo/Generated/ColorStyle.swift
  templateOptions:
    publicAccess: true

textStyles:
  file:
    key: OeN0WmQ5miixA849nZmcEN
    includedNodes:
      - 91%3A38
  destination: FugenDemo/Generated/TextStyle.swift
  templateOptions:
    publicAccess: true
    usingSystemFonts: false

images:
  file: https://www.figma.com/file/61xw2FQn61Xr7VVFYwiHHy/Fugen-Demo?node-id=91%3A63
  assets: FugenDemo/Resources/Images.xcassets/Generated
  destination: FugenDemo/Generated/Images.swift
  templateOptions:
    publicAccess: true

shadowStyles:
  file: https://www.figma.com/file/61xw2FQn61Xr7VVFYwiHHy/Fugen-Demo?node-id=236%3A4
  destination: FugenDemo/Generated/ShadowStyle.swift
  templateOptions:
    publicAccess: true
